use role accountadmin;

SELECT
  TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || T.TABLE_NAME as TableName, 
  count(C.TABLE_ID) as FileCount,
  avg(FILE_SIZE) / 1024 / 1024 as AvgFileSize_MB
FROM
  SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY C
  LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.TABLES T ON C.TABLE_ID = T.TABLE_ID
WHERE DELETED IS NOT NULL   
GROUP BY
  1
HAVING
  AvgFileSize_MB < 10 OR AvgFileSize_MB > 250;
